# -*- coding: utf-8 -*-
"""Cópia de aula2_exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOrfEbdoQ5Lp66vZyI2QNeHoXOzlb6WY

**Aula 2 - Exercícios**

Aqui vamos explorar DataFrames da biblioteca Pandas.

Carregue os dados do titanic (o mesmo do notebook aula2), e responda as perguntas abaixo.

url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'
"""

# Carregando bibliotecas
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Vamos praticar a manipulação de DataFrames usando uma base de dados de exemplo ("toy dataset")
# Vamos usar dados de passageiros do Titanic
# Link para os dados de exemplo:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'
# Comando do Pandas para ler um arquivo csv. Ele já entende que é um DataFrame:
titanic = pd.read_csv(url)
titanic.head()

"""1) Qual é a idade e o sexo do passageiro número 500?"""

print('A idade do passageiro número 500 é:')
titanic.iloc[500,3]

"""2) Qual é a idade e o sexo dos passageiros de 100 a 110?"""

print('A idade e o sexo dos passageiros de número entre 100 e 110, é:')
titanic.iloc[100:111,2:4]

"""3) Determine qual é a posição (índice) da primeira criança que aparece na lista. Em seguida, imprima todas as informações sobre essa criança.  """

titanic[(titanic['who']) == 'child']
titanic.iloc[7]

"""4) Use a função groupby() para agrupar dados de passageiros por sexo, classe e sobrevivência. Determine quantos homens que viajavam na 3a classe sobreviveram."""

sex_class_survived = titanic.groupby(['sex','class','alive'])
manthirdalive = sex_class_survived.get_group(('male','Third','yes'))
manthirdalive

"""5) Utilizando o grupo do item 4, use a função .mean() para determinar a idade média dos homens que viajavam na 3a classe e que sobreviveram."""

media = manthirdalive.mean(numeric_only=True)[['age']]
print(media)

"""6) Utilizando o grupo do item 4, use a função .mean() para determinar a idade média de homens e mulheres em cada classe e desfecho."""

sex_class_survived.mean(numeric_only=True)[['age']]

"""7) Utilizando o pacote matplotlib (plt), e o grupo de passageiros do item 4, faça um histograma das idades das mulheres da primeira classe que sobreviveram."""

mulheresprim = titanic.groupby(['sex','survived','pclass']).get_group(('female',1,1))
plt.hist(mulheresprim['age'])
plt.xlabel("idade(anos)")
plt.ylabel('contagem')
plt.title('Idade das mulheres da primeira classe vivas')
plt.show()

"""8) Utilizando o pacote matplotlib (plt), e o grupo de passageiros do item 4, faça um boxplot para comparar as idades dos homens da primeira, segunda e terceira classe que sobreviveram."""

homens.head(10)

homens1 = titanic.groupby(['sex','survived','pclass']).get_group(('male',1,1))
homens2 = titanic.groupby(['sex','survived','pclass']).get_group(('male',1,2))
homens3 = titanic.groupby(['sex','survived','pclass']).get_group(('male',1,3))
homens = pd.concat([homens1,homens2,homens3])
homens.boxplot(column='age', by='pclass')
plt.title('Comparação da idade dos homens por classe')
plt.xlabel("Classe")
plt.ylabel("Idade(anos)")
plt.show()