# -*- coding: utf-8 -*-
"""Cópia de aula1_exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17O0V62kGVAmy1gnSTDDlUqVbMQ30KF5J

**Aula 1 - Exercícios**

Para fazer esses exercícios, você precisará das bibliotecas abaixo.
"""

import numpy as np
import pandas as pd
import plotly.express as px
import math as mt
import datetime as dt

"""# Exercício 1

**1) Média de um conjunto de 5 valores**

Crie um vetor (array) com 5 valores entre 0 e 10 e armazene em uma variável chamada "notas". Calcule a média desses valores e imprima a resposta.

Obs: experimente calcular a média de dois jeitos diferentes. Some os valores 3 divida por 5. E experimente usar a função np.mean().

https://numpy.org/doc/stable/reference/generated/numpy.mean.html
"""

notas = range(1,6)
média = np.mean(notas)
print(média)

"""# Exercício 2

**2) Série temporal de concentração**

a) Crie um vetor (array) com valores inteiros de 1 a 30, que representam os dias de um mês.

b) Vamos gerar 30 valores aleatórios entre 0 e 100 para representar a concentração de um determinado poluente. Veja na célula abaixo como fazer isso com a função random.default_rng() do numpy.

c) Junte esse dois vetores em um dataframe (tabela de dados).

d) Calcule a média da concentração e imprima o resultado.

e) Faça um gráfico da concentração em função do dia.
"""

# Exemplo de como gerar 3 número inteiros aleatórios entre 0 e 10
import numpy as np
gerador = np.random.default_rng()
valores = gerador.integers(low=0, high=10, size=3)
valores

dias = list(range(1,31))
gerador = np.random.default_rng()
valores = gerador.integers(low=0,high=100, size = 30)
print('Este é o vetor dias')
print(dias)
print('Este é o vetor concentrações')
print(valores)
Série = pd.DataFrame(
    {"Dia": dias,
     "Concentração": valores,})
print(Série)
média = np.mean(valores)
print('Média das concentrações')
print(média)
fig1 = px.line(Série,x='Dia',y='Concentração',markers=True,
               labels={"dias": "Dia de medida", "valores": "Concentração(ppb)"},
               title= "Concentração em função do dia")
fig1.show()

"""# Exercício 3

**3) Acessando subconjuntos de dados**

Utilize o dataframe criado no item anterior.

a) Imprimir a concentração nos 7 primeiros dias. Use a função .loc[] do pandas.

b) Calcular a média da concentração nos 7 primeiros dias. Use a função .mean() do pandas.

c) Imprimir o valor da máxima concentração. Use a função .max() do pandas.

d) Em que dia ocorreu a máxima concentração? Para descobrir isso, use a função .idxmax() do pandas. Ela dá como resposta *a posição* (índice ou linha) do dataframe onde está o valor máximo de concentração.
"""

primeiros = Série.loc[range(0,7)]
print(primeiros)

Médiaconc = primeiros.Concentração.mean()
print('Esta é a média da concentração nos primeiros 7 dias.')
print(Médiaconc)

Máxconc = Série.Concentração.max()
print('Este é o valor máximo da concentração')
print(Máxconc)

Diamáx = Série.Concentração.idxmax()
print('Esta é a linha onde está a maior concentração')
print(Diamáx)

"""# Extra

**Extra**

Se quiser fazer mais exercícios, reproduza alguns exemplos dos capítulos 2 e 3 do livro abaixo:

https://www.dropbox.com/scl/fi/2vv07k6zmtquhk95oxxox/Allen-B.-Downey-Pense-em-Python-2002.pdf?rlkey=mk1ajr4ei7m55mylpvgxcotuz&dl=0

Exercícios do livro
"""

n = 2
x = y = 1
print(n)
print(x)

print('Olá');
print('Hallo').

x = 1
y =2
print(xy)

volume = (4/3)*mt.pi*(5**3)
print(volume)

atacado = (25.95*0.6)+(3+(0.75*60))
print ('O valor dos 60 livros, em reais é de:')
print (atacado)

horainicial = datetime.time(06,52,0o)
pace1 = datetime.time(00,08,15)
pace2 = datetime.time(00,07,12)
horafinal = (horainicial+(1*pace1))

