# -*- coding: utf-8 -*-
"""Exercício dados ATTO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYCgVjnaEnSDqHhcvxCRyj-pP7_8d6-J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

# Primeiramente, copiando e colando o endereço do arquivo (URL)
URL = 'https://drive.google.com/file/d/1xEn5aZ8SG-So9zUdDBQnrZLFRt2sOJ0N/view?usp=drive_link'

separador_decimal = '.'
cabec = 0
delimitador = ';'
fimdalinha = '\n'

file_id = URL.split('/d/')[1].split('/')[0]
dados_csv_url = f'https://drive.google.com/uc?export=download&id={file_id}'
print('Original: ', URL)
print('Modificado: ', dados_csv_url)

dados_csv = pd.read_csv(dados_csv_url, decimal = separador_decimal, header = cabec,
                        sep = delimitador, lineterminator = fimdalinha)
dados_csv

from datetime import datetime, timedelta

# referência: 2014-01-01 00:00
ref = datetime(2014, 1, 1)

# Assuming 'TimeUTC' column contains Unix timestamps in seconds
# Convert the 'TimeUTC' column to datetime objects, and add the offset using timedelta
dados_csv['TimeUTC'] = pd.to_datetime(dados_csv['TimeUTC'], unit='s', origin='unix')
dados_csv['TimeUTC'] = dados_csv['TimeUTC'] + timedelta(days=(ref - datetime(1974, 1, 1)).days) # Correctly adding the offset using timedelta

# Indexando o dataframe pela data
dados_csv.set_index('TimeUTC', inplace=True)
dados_csv.head()

timedelta(days=(ref - datetime(1970, 1, 1)).days)

# Alterando os dados 999999.0 para NaN
dados_csv = dados_csv.replace(999999.0, np.nan)
dados_csv

#Fazendo um gráfico da série temporal de CO2, com o equipamento D8, para todas as diferentes alturas:
CO2_1 = 'D8CO2_1'
CO2_3 = 'D8CO2_3'
CO2_4 = 'D8CO2_4'
CO2_5 = 'D8CO2_5'
CO2_6 = 'D8CO2_6'
Serie_temporal = plt.plot(dados_csv.index, dados_csv[CO2_1])
Serie_temporal3 = plt.plot(dados_csv.index, dados_csv[CO2_3])
Serie_temporal4 = plt.plot(dados_csv.index, dados_csv[CO2_4])
Serie_temporal5 = plt.plot(dados_csv.index, dados_csv[CO2_5])
Serie_temporal6 = plt.plot(dados_csv.index, dados_csv[CO2_6])
plt.xlabel('Data')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Série temporal de CO2 em diferentes níveis equipamento D8')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

#Agrupando os dados por mês e fazendo a média mensal:
dados_csv_mes = dados_csv.resample('ME').mean()
dados_csv_mes

#Assim, temos a série temporal mensal, nos diferentes níveis do equipamento D8:
Serie_temporal_mes = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_1])
Serie_temporal_mes3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_3])
Serie_temporal_mes4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_4])
Serie_temporal_mes5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_5])
Serie_temporal_mes6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_6])
plt.xlabel('Data(mês)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Série mensal de CO2 em diferentes níveis')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

#Fazendo a mesma coisa, agora com as médias de diferentes horas do dia:
dados_csv.index = dados_csv.index.tz_localize('UTC')
horamanaus = dados_csv.index.tz_convert('America/Manaus') # Correctly convert the index to the 'America/Manaus' timezone.
hora = horamanaus.hour # Extract the hour from the converted timezone
dados_csv_hora = dados_csv.groupby(hora).mean()
dados_csv_hora

#Agora, o gráfico do ciclo diurno médio do equipamento D8:
Serie_temporal_hora = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_1])
Serie_temporal_hora3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_3])
Serie_temporal_hora4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_4])
Serie_temporal_hora5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_5])
Serie_temporal_hora6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_6])
plt.xlabel('Hora (Local)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Ciclo diurno médio de CO2 em diferentes níveis')
plt.legend(['4 m', '28 m', '38 m', '53 m', '79 m'])

#Refazendo as análises de CO2, agora com o equipamento D9:
CO2_11 = 'D9CO2_1'
CO2_33 = 'D9CO2_3'
CO2_44 = 'D9CO2_4'
CO2_55 = 'D9CO2_5'
CO2_66 = 'D9CO2_6\r'
Serie_temporal = plt.plot(dados_csv.index, dados_csv[CO2_11])
Serie_temporal3 = plt.plot(dados_csv.index, dados_csv[CO2_33])
Serie_temporal4 = plt.plot(dados_csv.index, dados_csv[CO2_44])
Serie_temporal5 = plt.plot(dados_csv.index, dados_csv[CO2_55])
Serie_temporal6 = plt.plot(dados_csv.index, dados_csv[CO2_66])
plt.xlabel('Data')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Série temporal de CO2 em diferentes níveis equipamento D9')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

#Assim, temos a série temporal mensal, nos diferentes níveis do equipamento D9:
Serie_temporal_mess = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_11])
Serie_temporal_mess3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_33])
Serie_temporal_mess4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_44])
Serie_temporal_mess5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_55])
Serie_temporal_mess6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_66])
plt.xlabel('Data(mês)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Série mensal de CO2 em diferentes níveis equipamento D9')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])



#Comparando os dois equipamentos:
Serie_temporal_mes = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_1], color='purple', linestyle='solid')
Serie_temporal_mess = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_11], color='purple', linestyle='dashed')
Serie_temporal_mes3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_3], color='green', linestyle='dashed')
Serie_temporal_mess3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_33], color='green', linestyle='solid')
Serie_temporal_mes4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_4], color='black', linestyle='solid')
Serie_temporal_mess4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_44], color='black', linestyle='dashed')
Serie_temporal_mess5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_55], color='blue', linestyle='solid')
Serie_temporal_mes5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_5], color='blue', linestyle='dashed')
Serie_temporal_mes6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_6], color='red', linestyle='solid')
Serie_temporal_mess6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO2_66], color='red', linestyle='dashed')
plt.xlabel('Data(mês)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Comparação das séries mensais de CO2 em diferentes níveis')
plt.legend(['4 m (D8)', '4 m (D9)', '24 m (D8)', '24 m (D9)', '38 m (D8)', '38 m (D9)',
 '53 m (D8)', '53 m (D9)', '79 m (D8)', '79 m (D9)'], bbox_to_anchor=(1.05, 1), loc='upper left')

#Correlação entre os dados dos equipamentos D8 e D9:
plt.scatter(dados_csv[CO2_1], dados_csv[CO2_11])
plt.xlabel('D8 - CO2(ppm)')
plt.ylabel('D9 - CO2(ppm)')
plt.title('Correlação entre os dados dos equipamentos D8 e D9, das concentrações de CO2')

#Adicionando uma reta:
modelo = linear_model.LinearRegression(fit_intercept=True)
#Considerando que essa função não aceita dados faltantes:
dados_para_modelo = dados_csv[[CO2_1, CO2_11]].dropna()
x = dados_para_modelo[CO2_1].values.reshape(-1, 1)
y = dados_para_modelo[CO2_11]
modelo.fit(x, y)

print("Coeficiente angular (a):", modelo.coef_)
print("Coeficiente linear (b):", modelo.intercept_)

y_calculado = modelo.predict(x)

plt.scatter(dados_csv[CO2_1], dados_csv[CO2_11])
plt.plot(x, y_calculado, color='red')
plt.ylabel('D8 - CO2(ppm)')
plt.xlabel('D9 - CO2(ppm)')
plt.title('Correlação entre os dados dos equipamentos D8 e D9, das concentrações de CO2')

# Calculando o Coeficiente de Pearson da correlação entre os dados dos dois equipamentos:
from sklearn.feature_selection import r_regression
r = r_regression(x, y)
print("Coeficiente de Pearson:", r[0])

# O Ciclo diurno médio do equipamento D9:
Serie_temporal_horaa = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_11])
Serie_temporal_horaa3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_33])
Serie_temporal_horaa4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_44])
Serie_temporal_horaa5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_55])
Serie_temporal_horaa6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_66])
plt.xlabel('Hora (Local)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Ciclo diurno médio de CO2 em diferentes níveis do equipamento D9')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

#Comparando o Ciclo Diurno médio dos equipamentos:
Serie_temporal_hora = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_1], color='black',linestyle='solid')
Serie_temporal_horaa = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_11], color='yellow', linestyle='dashed')
Serie_temporal_hora3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_3], color='green', linestyle='solid')
Serie_temporal_hora4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_4], color='red', linestyle='solid')
Serie_temporal_hora5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_5], color='brown', linestyle='solid')
Serie_temporal_hora6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_6], color='yellow', linestyle='solid')
Serie_temporal_horaa3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_33], color='black', linestyle='dashed')
Serie_temporal_horaa4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_44], color='green', linestyle='dashed')
Serie_temporal_horaa5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_55], color='red', linestyle='dashed')
Serie_temporal_horaa6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO2_66], color='brown', linestyle='dashed')
plt.xlabel('Hora (Local)')
plt.ylabel('Concentração de CO2 (ppm)')
plt.title('Comparação dos ciclos diurnos médio de CO2 em diferentes níveis')
plt.legend(['Equipamento D8', 'Equipamento D9'])

# Agora, fazendo as séries temporais para o CH4:
CH4_1 = 'D9CH4_1'
CH4_3 = 'D9CH4_3'
CH4_4 = 'D9CH4_4'
CH4_5 = 'D9CH4_5'
CH4_6 = 'D9CH4_6'
Serie_temporal = plt.plot(dados_csv.index, dados_csv[CH4_1])
Serie_temporal3 = plt.plot(dados_csv.index, dados_csv[CH4_3])
Serie_temporal4 = plt.plot(dados_csv.index, dados_csv[CH4_4])
Serie_temporal5 = plt.plot(dados_csv.index, dados_csv[CH4_5])
Serie_temporal6 = plt.plot(dados_csv.index, dados_csv[CH4_6])
plt.xlabel('Data')
plt.ylabel('Concentração de CH4 (ppb)')
plt.title('Série temporal de CH4 em diferentes níveis equipamento D8')
plt.legend(['Nível 1', 'Nível 3', 'Nível 4', 'Nível 5', 'Nível 6'])

#Assim, temos a série temporal mensal de CH4, nos diferentes níveis do equipamento D9:
Serie_temporal_mes = plt.plot(dados_csv_mes.index, dados_csv_mes[CH4_1])
Serie_temporal_mes3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CH4_3])
Serie_temporal_mes4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CH4_4])
Serie_temporal_mes5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CH4_5])
Serie_temporal_mes6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CH4_6])
plt.xlabel('Data(mês)')
plt.ylabel('Concentração de CH4 (ppb)')
plt.title('Série mensal de CH4 em diferentes níveis')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

# O Ciclo diurno médio do CH4, é:
Serie_temporal_hora = plt.plot(dados_csv_hora.index, dados_csv_hora[CH4_1])
Serie_temporal_hora3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CH4_3])
Serie_temporal_hora4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CH4_4])
Serie_temporal_hora5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CH4_5])
Serie_temporal_hora6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CH4_6])
plt.xlabel('Hora(Local)')
plt.ylabel('Concentração de CH4 (ppb)')
plt.title('Ciclo diurno médio de CH4 em diferentes níveis')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

# Por fim, faremos as análises para os dados de CO:
CO_1 = 'D8CO1_1'
CO_3 = 'D8CO1_3'
CO_4 = 'D8CO1_4'
CO_5 = 'D8CO1_5'
CO_6 = 'D8CO1_6'
Serie_temporal = plt.plot(dados_csv.index, dados_csv[CO_1])
Serie_temporal3 = plt.plot(dados_csv.index, dados_csv[CO_3])
Serie_temporal4 = plt.plot(dados_csv.index, dados_csv[CO_4])
Serie_temporal5 = plt.plot(dados_csv.index, dados_csv[CO_5])
Serie_temporal6 = plt.plot(dados_csv.index, dados_csv[CO_6])
plt.xlabel('Data')
plt.ylabel('Concentração de CO (ppb)')
plt.title('Série temporal de CO em diferentes níveis equipamento D8')

#Assim, temos a série temporal mensal de C0, nos diferentes níveis:
Serie_temporal_mes = plt.plot(dados_csv_mes.index, dados_csv_mes[CO_1])
Serie_temporal_mes3 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO_3])
Serie_temporal_mes4 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO_4])
Serie_temporal_mes5 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO_5])
Serie_temporal_mes6 = plt.plot(dados_csv_mes.index, dados_csv_mes[CO_6])
plt.xlabel('Data(mês)')
plt.ylabel('Concentração de CO (ppb)')
plt.title('Série mensal de CO em diferentes níveis')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])

# O Ciclo diurno médio do CO, é:
Serie_temporal_hora = plt.plot(dados_csv_hora.index, dados_csv_hora[CO_1])
Serie_temporal_hora3 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO_3])
Serie_temporal_hora4 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO_4])
Serie_temporal_hora5 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO_5])
Serie_temporal_hora6 = plt.plot(dados_csv_hora.index, dados_csv_hora[CO_6])
plt.xlabel('Hora (Local)')
plt.ylabel('Concentração de CO(ppb)')
plt.title('Ciclo diurno médio de CO em diferentes níveis')
plt.legend(['4 m', '24 m', '38 m', '53 m', '79 m'])
